# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Example' do
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GoogleMapsDirections', :path => '../'
  pod 'GooglePlacesAPI', :path => '../'

end
