# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GoogleMapsDirections', :path => '../GoogleMapsDirections.podspec'
  pod 'GooglePlacesAPI', :path => '../GooglePlacesAPI.podspec'

end
