# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

def dependency_pods
	pod 'ObjectMapper', '~> 1.0'
	pod 'Alamofire', '~> 3.0'
end

target 'GoogleMapsDirections iOS' do
	dependency_pods
end

target 'GoogleMapsDirections OSX' do
	dependency_pods
end

target 'GoogleMapsDirections watchOS' do
	dependency_pods
end

target 'GoogleMapsDirections tvOS' do
	dependency_pods
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'Alamofire' or target.name == 'ObjectMapper'
			target.build_configurations.each do |config|
				config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
			end
		end
	end
end
