# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'GoogleMapDirections' do

pod 'ObjectMapper', '~> 1.0'
pod 'Alamofire', '~> 3.0'

end

target 'GoogleMapDirectionsTests' do

end

